### ISSUE TITLE
Cannot build application with arcgis-webpack-plugin 4.16.3

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-webpack-plugin#100]
## Description

Hello,

Since 4.17 has been released, I can no longer build my app with arcgis-webpack-plugin 4.16.3 after having deleted node_modules folder or in GitLabCI.
It throws the following error when running ```webpack``` command:
```Error: ENOENT: no such file or directory, open '/Users/nicolas/Workspace/mapcern/node_modules/dojo/dojo.js'```

Debugging this error I noticed that if you install arcgis-webpack-plugin 4.16.3, it will automatically install as a dependency arcgis-js-api 4.17 and I believe the issue is coming from that.

## Expected Behavior

Should be able to build my application using 4.16 version of the API.

## Actual Behavior

Build fails.

## Possible Fix

Fix arcgis-webpack-plugin dependencies tree.
If I upgrade arcgis-webpack-plugin to 4.17, it works but then it is 4.17 which is installed.

## Steps to Reproduce

1. Build a simple app with arcgis-webpack-plugin 4.16.3 (maybe using arcgis-js-cli)
2. Install dependencies with ```npm install```
3. Build the app with ```webpack```

## Your Environment

* Version used: 4.16.3
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project if available:

Thanks !

**Comment by odoe** [comment]
This fixed in `4.16.4`.

**Comment by Biboba** [comment]
Thanks !
Don't see it though:
https://github.com/Esri/arcgis-webpack-plugin/tree/4.16.4

**Comment by odoe** [comment]
it's not a github release

**Comment by Biboba** [comment]
Just updated to 4.16.4 but it still does not work.
I now have the following error:
```
webpack --mode production

Error: Dojo loader version does not match the version of Dojo.
Loader version = 1.14.2.
Dojo version = 1.16.3.
You may need to rebuild the Dojo loader.
Refer to https://github.com/OpenNTF/dojo-webpack-plugin/blob/master/README.md#building-the-dojo-loader
```

Thanks !

**Comment by odoe** [comment]
I tightened up the dojo versions in 4.16.5, try that one. If not, make sure you're app doesn't have a dojo dep that might be taking precedence.

**Comment by Biboba** [comment]
Thanks the quick fix @odoe !
With 4.16.5, it works 👍
